name: Moodle Plugin CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3

      mariadb:
        image: mariadb:10.11
        env:
          MYSQL_USER: 'root'
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
          MYSQL_CHARACTER_SET_SERVER: "utf8mb4"
          MYSQL_COLLATION_SERVER: "utf8mb4_unicode_ci"
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 3

    strategy:
      fail-fast: false
      matrix:
        include:
          - php: '8.2'
            moodle-branch: 'MOODLE_500_STABLE'
            database: pgsql
          - php: '8.3'
            moodle-branch: 'MOODLE_500_STABLE'
            database: pgsql
          - php: '8.4'
            moodle-branch: 'MOODLE_500_STABLE'
            database: pgsql
          - php: '8.2'
            moodle-branch: 'MOODLE_500_STABLE'
            database: mariadb
          - php: '8.3'
            moodle-branch: 'MOODLE_500_STABLE'
            database: mariadb
          - php: '8.4'
            moodle-branch: 'MOODLE_500_STABLE'
            database: mariadb
          - php: '8.1'
            moodle-branch: 'MOODLE_405_STABLE'
            database: pgsql
          - php: '8.2'
            moodle-branch: 'MOODLE_405_STABLE'
            database: pgsql
          - php: '8.3'
            moodle-branch: 'MOODLE_405_STABLE'
            database: pgsql
          - php: '8.1'
            moodle-branch: 'MOODLE_405_STABLE'
            database: mariadb
          - php: '8.2'
            moodle-branch: 'MOODLE_405_STABLE'
            database: mariadb
          - php: '8.3'
            moodle-branch: 'MOODLE_405_STABLE'
            database: mariadb
          - php: '8.1'
            moodle-branch: 'MOODLE_404_STABLE'
            database: pgsql
          - php: '8.2'
            moodle-branch: 'MOODLE_404_STABLE'
            database: pgsql
          - php: '8.3'
            moodle-branch: 'MOODLE_404_STABLE'
            database: pgsql
          - php: '8.1'
            moodle-branch: 'MOODLE_404_STABLE'
            database: mariadb
          - php: '8.2'
            moodle-branch: 'MOODLE_404_STABLE'
            database: mariadb
          - php: '8.3'
            moodle-branch: 'MOODLE_404_STABLE'
            database: mariadb
          - php: '8.0'
            moodle-branch: 'MOODLE_403_STABLE'
            database: pgsql
          - php: '8.1'
            moodle-branch: 'MOODLE_403_STABLE'
            database: pgsql
          - php: '8.2'
            moodle-branch: 'MOODLE_403_STABLE'
            database: pgsql
          - php: '8.0'
            moodle-branch: 'MOODLE_403_STABLE'
            database: mariadb
          - php: '8.1'
            moodle-branch: 'MOODLE_403_STABLE'
            database: mariadb
          - php: '8.2'
            moodle-branch: 'MOODLE_403_STABLE'
            database: mariadb

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          path: plugin

      - name: Moodle CI PHP ${{ matrix.php }} Moodle ${{ matrix.moodle-branch }} DB ${{ matrix.database }}
        uses: gfrancv/moodle-plugin-ci-action@v1.1.0
        with:
          php-version: ${{ matrix.php }}
          moodle-branch: ${{ matrix.moodle-branch }}
          database: ${{ matrix.database }}
          plugin-path: ./plugin