name: Create Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build:
    name: Build and Release Plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout plugin code
        uses: actions/checkout@v2

      - name: Prepare release zip
        run: |
          mkdir -p release/viewer3d
          rsync -av --exclude-from='.rsync-exclude' . release/viewer3d/
          cd release
          zip -r mod_viewer3d_${{ github.ref_name }}.zip viewer3d
          cd ..

      - name: Publish release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: release/mod_viewer3d_${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}